name: Serenity Screenplay CI

# Run the workflow on push or pull request events to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: selenium/standalone-chrome:latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: 'main'

      # Step 2: Set up JDK (Java 14 in this example, modify as needed)
      - name: Set up JDK 14
        uses: actions/setup-java@v3
        with:
          java-version: '19.0.0+36'
          distribution: 'temurin' # Choose a JDK provider like Temurin or Zulu
          cache: maven

      # Step 3: Set up Maven and dependencies
      - name: Install dependencies
        run: mvn install -DskipTests=true

      # Step 4: Run the Serenity tests
      - name: Run Serenity Screenplay Tests
        run: mvn clean verify

      # Step 5: Upload Serenity Reports (optional but recommended)
      - name: Upload Serenity Reports
        uses: actions/upload-artifact@v3
        with:
          name: serenity-report
          path: target/site/serenity/
