name: Serenity Screenplay CI

# Run the workflow on push or pull request events to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up JDK (Java 14 in this example, modify as needed)
      - name: Set up JDK 14
        uses: actions/setup-java@v3
        with:
          java-version: '19.0.0+36'
          distribution: 'temurin' # Choose a JDK provider like Temurin or Zulu
          cache: maven
      
      # Step 3: Install Chrome
      - name: Install Google Chrome
        run: sudo apt-get install -y google-chrome-stable

      # Step 4: Install ChromeDriver
      - name: Install ChromeDriver
        run: |
          CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+')
          curl -sS -o /tmp/chromedriver.zip https://storage.googleapis.com/chrome-for-testing-public/129.0.6668.89/linux64/chromedriver-linux64.zip
          sudo unzip /tmp/chromedriver.zip -d /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver-linux64/chromedriver
          
      # Step 3: Set up Maven and dependencies
      - name: Install dependencies
        run: mvn install

      # Step 5: Upload Serenity Reports (optional but recommended)
      - name: Upload Serenity Reports
        uses: actions/upload-artifact@v3
        with:
          name: serenity-report
          path: target/site/serenity/
